blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/marovira/helios-ml/discussions
    about: >
      For usage questions and general discussion, please use GitHub Discussions rather
      than opening an issue.
