name: "Publish"

on:
  release:
    types: [published]

jobs:
  check:
    uses: ./.github/workflows/tests.yml

  publish:
    needs: check
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/helios-ml
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build Helios
        run: |
          uv build

      - name: Publish Helios
        uses: pypa/gh-action-pypi-publish@release/v1

  docs:
    needs: publish
    uses: ./.github/workflows/docs.yml
